# Generated by Django 3.0.3 on 2020-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('uf', 'unifox'), ('em', 'emotion'), ('tl', 'teamlog'), ('l7', 'layer7'), ('tl', 'teamlog')], max_length=2)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
