# Generated by Django 3.0.3 on 2020-03-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200216_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
