# Generated by Django 3.1.7 on 2021-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200216_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
