# Generated by Django 3.0.3 on 2020-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.CharField(choices=[('uf', 'unifox'), ('em', 'emotion'), ('tl', 'teamlog'), ('l7', 'layer7'), ('nf', 'nefus')], max_length=2),
        ),
    ]
